ARG project=nestjs_sandbox

# build phase
FROM node:14.5.0

WORKDIR /${project}

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN npm run test

ENTRYPOINT [ "npm", "run", "start:dev"]



